using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker_EN.Camera;

/// <summary>
/// Window for displaying a captured photograph with metadata.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STPhotoWindow : FancyWindow
{
    public STPhotoWindow()
    {
        RobustXamlLoader.Load(this);
    }

    /// <summary>
    /// Set the photo metadata. Image will show when SetTexture is called.
    /// </summary>
    public void SetMetadata(Guid photoId, string photographerName, TimeSpan timeTaken)
    {
        LoadingLabel.Visible = true;
        PhotoTexture.Texture = null;

        PhotographerLabel.Text = Loc.GetString("st-photo-photographer", ("name", photographerName));

        var minutes = (int) timeTaken.TotalMinutes;
        var seconds = timeTaken.Seconds;
        TimeLabel.Text = Loc.GetString("st-photo-time", ("minutes", minutes), ("seconds", seconds));
    }

    /// <summary>
    /// Display the photo texture and hide the loading label.
    /// </summary>
    public void SetTexture(Texture texture)
    {
        PhotoTexture.Texture = texture;
        LoadingLabel.Visible = false;
    }
}
