using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Content.Shared.Dataset;
using Content.Shared.Portraits;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Content.Shared.Random.Helpers;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutWindow : FancyWindow
{
    public event Action<string>? OnNameChanged;
    public event Action<ProtoId<LoadoutGroupPrototype>, ProtoId<LoadoutPrototype>>? OnLoadoutPressed;
    public event Action<ProtoId<LoadoutGroupPrototype>, ProtoId<LoadoutPrototype>>? OnLoadoutUnpressed;

    public event Action<string>? OnPortraitSelected;

    private readonly List<LoadoutGroupContainer> _groups = new();
    private PortraitSelector? _portraitSelector;

    public HumanoidCharacterProfile Profile;

    private int _maxLoadoutNameLength;

    public LoadoutWindow(HumanoidCharacterProfile profile, RoleLoadout loadout, RoleLoadoutPrototype proto, ICommonSession session, IDependencyCollection collection, JobPrototype? jobProto = null)
    {
        RobustXamlLoader.Load(this);
        Profile = profile;
        var protoManager = collection.Resolve<IPrototypeManager>();
        var configManager = collection.Resolve<IConfigurationManager>();

        _maxLoadoutNameLength = configManager.GetCVar(CCVars.MaxLoadoutNameLength);
        RoleNameEdit.IsValid = text => text.Length <= _maxLoadoutNameLength;

        if (!proto.CanCustomizeName)
        {
            RoleNameBox.Visible = false;
        }
        else
        {
            var name = loadout.EntityName;

            LoadoutNameLabel.Text = proto.NameDataset == null ?
                Loc.GetString("loadout-name-edit-label") :
                Loc.GetString("loadout-name-edit-label-dataset");

            RoleNameEdit.ToolTip = Loc.GetString(
                "loadout-name-edit-tooltip",
                ("max", _maxLoadoutNameLength));
            RoleNameEdit.Text = name ?? string.Empty;
            RoleNameEdit.OnTextChanged += args => OnNameChanged?.Invoke(args.Text);
        }

        if (proto.Groups.Count == 0)
        {
            LoadoutGroupsContainer.Visible = false;
            SetSize = Vector2.Zero;
        }
        else
        {
            foreach (var group in proto.Groups)
            {
                if (!protoManager.Resolve(group, out var groupProto))
                    continue;

                if (groupProto.Hidden)
                    continue;

                var container = new LoadoutGroupContainer(profile, loadout, protoManager.Index(group), session, collection);
                LoadoutGroupsContainer.AddTab(container, Loc.GetString(groupProto.Name));
                _groups.Add(container);

                container.OnLoadoutPressed += args =>
                {
                    OnLoadoutPressed?.Invoke(group, args);
                };

                container.OnLoadoutUnpressed += args =>
                {
                    OnLoadoutUnpressed?.Invoke(group, args);
                };
            }
        }

        // Portrait tab — filtered by current role
        var jobId = jobProto?.ID;
        Robust.Shared.Log.Logger.GetSawmill("portrait").Info($"Portrait tab opened for job: {jobId}");
        var portraits = new List<CharacterPortraitPrototype>();
        foreach (var portrait in protoManager.EnumeratePrototypes<CharacterPortraitPrototype>())
        {
            var match = portrait.JobId == jobId;
            Robust.Shared.Log.Logger.GetSawmill("portrait").Debug($"Portrait {portrait.ID}: jobId={portrait.JobId}, match={match}");
            if (!match)
                continue;

            portraits.Add(portrait);
        }

        Robust.Shared.Log.Logger.GetSawmill("portrait").Info($"Found {portraits.Count} portraits for job {jobId}");

        _portraitSelector = new PortraitSelector();
        _portraitSelector.Setup(portraits, Profile.SelectedPortraitId);
        _portraitSelector.OnPortraitSelected += id => OnPortraitSelected?.Invoke(id);
        LoadoutGroupsContainer.AddTab(_portraitSelector, "Portrait");
    }

    public void RefreshLoadouts(RoleLoadout loadout, ICommonSession session, IDependencyCollection collection)
    {
        foreach (var group in _groups)
        {
            group.RefreshLoadouts(Profile, loadout, session, collection);
        }
    }
}
